### ISSUE TITLE
用fastgit无法登录git

### ISSUE THREAD

**Issue by hdtopku** [FastGitORG/uptime#221]
想要用fastgit登录github，点击登录，就返回错误。请问怎么解决？
![image](https://user-images.githubusercontent.com/14859466/164619229-50f4b8d8-bee4-479c-94c2-23552ab1fe93.png)
![image](https://user-images.githubusercontent.com/14859466/164619395-93e7e40a-22da-4a7f-b1db-5e1bc52ff80d.png)

**Comment by KevinZonda** [comment]
It is not a g
